name: Plugin Tests

on:
  push:
    branches:
      - test-ye
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  plugin-test:
    runs-on: [ self-hosted, TE_FL ]
    defaults:
      run:
        shell: bash
    container:
      image: localhost:5000/flagscale-cuda12.8.1-torch2.7.1-python3.10-te2.9:20260209
      ports:
        - 80:80
      options: >-
        --gpus all 
        --shm-size=500g 
        --privileged 
        --ipc=host 
        --ulimit memlock=-1 
        --ulimit stack=67108864 
        --ulimit nofile=65535:65535 
        --user root
        --pull always
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6.0.1
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          ssh-strict: true
          ssh-user: git
          persist-credentials: true
          clean: true
          sparse-checkout-cone-mode: true
          fetch-tags: false
          show-progress: true
          lfs: false
          submodules: recursive
          set-safe-directory: true
      
      - name: Install dependencies and build transformer_engine
        timeout-minutes: 60
        env:
          NVTE_FRAMEWORK: pytorch
          TE_WITH_NCCL: 1
        run: |
          echo "Install transformer_engine"
          source /opt/miniconda3/etc/profile.d/conda.sh
          conda activate flagscale-train
          pip install transformers expecttest
          pip install --no-build-isolation -vvv . --no-deps

          # Verify installation
          python3 tests/pytorch/test_sanity_import.py

      - name: GPU Usage Check / Verification
        run: |
          source .github/workflows/scripts/gpu_check.sh
          wait_for_gpu

      - name: Plugin Test
        timeout-minutes: 30
        run: |
          source /opt/miniconda3/etc/profile.d/conda.sh
          conda activate flagscale-train

          pip install pytest
          torchrun --nproc_per_node=8 -m pytest -q -x -p no:warnings transformer_engine/plugin/tests
